site_name: Apuntes Sistemas inform√°ticos
site_url: https://jogonar-rgb.github.io/Sistemas_informaticos/


nav:
  - Home: index.md
  - Apuntes:
    - Redes: redes.md
    - Hardware: hardware.md


theme: readthedocs



extra_css:
  - css/extra.css